/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.pi_2018_2;

import java.sql.PreparedStatement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodol
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    public static Banco banco;
    public static Conta conta;
    Tabela priceSimulado;
    Tabela sacSimulado;
    int i = 0;
    DecimalFormat formato = new DecimalFormat("#,###,##0.00");

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    public TelaPrincipal(Banco banco, Conta conta) {
        initComponents();
        this.banco = banco;
        this.conta = conta;
        
        jTextField1.setText(""+formato.format(conta.getRenda()));
        jTextField2.setText(""+formato.format(conta.getDivida()));
        
        botaoPrice.setEnabled(false);
        botaoSac.setEnabled(false);
        
//        buscar tabela1 e tabela2
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaPrice = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaSac = new javax.swing.JTable();
        botaoPrice = new javax.swing.JButton();
        botaoSac = new javax.swing.JButton();
        botaoSimular = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Renda:");

        jLabel7.setText("Valor do emprestimo:");

        jLabel8.setText("Numero de parcelas:");

        tabelaPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelaPrice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SI", "Juros", "Amortizacao", "PMT", "SF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelaPrice);

        tabelaSac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelaSac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SI", "Juros", "Amortizacao", "PMT", "SF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabelaSac);

        botaoPrice.setText("Pegar emprestimo PRICE");
        botaoPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPriceActionPerformed(evt);
            }
        });

        botaoSac.setText("Pegar emprestimo SAC");
        botaoSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSacActionPerformed(evt);
            }
        });

        botaoSimular.setText("Simular");
        botaoSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSimularActionPerformed(evt);
            }
        });

        jLabel9.setText("PRICE");

        jLabel10.setText("SAC");

        jLabel1.setText("Pagando:");

        jTextField1.setEditable(false);
        jTextField1.setText("\"Valor da renda\"");

        jTextField2.setEditable(false);
        jTextField2.setText("\"Valor sendo pago\"");

        jLabel2.setText("Taxa:");

        jLabel3.setText("%");

        jLabel4.setText("Total a pagar:");

        jLabel6.setText("R$");

        jLabel12.setText("Total a pagar:");

        jLabel11.setText("R$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(botaoSimular)
                    .addComponent(jLabel1)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(319, 319, 319))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botaoPrice)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botaoSac)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(botaoSimular))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoPrice)
                            .addComponent(botaoSac)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Simulacao de parcelas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSimularActionPerformed
        
        double emprestimo =  Double.parseDouble(jTextField3.getText());
        int parcelas = Integer.parseInt(jTextField4.getText());
        double taxa = Double.parseDouble(jTextField5.getText()) / 100;
        
        Calculo calculo = new Calculo();
        
        priceSimulado = calculo.tabelaPrice(emprestimo, parcelas, taxa);
        sacSimulado = calculo.tabelaSac(emprestimo, parcelas, taxa);
        
        preencherPriceSimulado(priceSimulado);
        jTextField6.setText(formato.format(somaPmt(priceSimulado)));
        preencherSacSimulado(sacSimulado);
        jTextField7.setText(formato.format(somaPmt(sacSimulado)));
        
        if (priceSimulado.getPmt().get(0) < conta.getRenda() * 0.3 - conta.getDivida()) {
            botaoPrice.setEnabled(true);
        }else{
            botaoPrice.setEnabled(false);
        }
        if (sacSimulado.getPmt().get(0) < conta.getRenda() * 0.3 - conta.getDivida()) {
            botaoSac.setEnabled(true);
        }else{
            botaoSac.setEnabled(false);
        }
        
    }//GEN-LAST:event_botaoSimularActionPerformed

    private void botaoPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPriceActionPerformed
        
        priceSimulado.setConta(conta);
        
        String stringSi = "{" + priceSimulado.getSi().get(0);
        for (int i = 1; i < priceSimulado.getSi().size(); i++) {
            stringSi += "," + priceSimulado.getSi().get(i);
        }
        stringSi += "}";
        
        String stringJuros = "{" + priceSimulado.getJuros().get(0);
        for (int i = 1; i < priceSimulado.getJuros().size(); i++) {
            stringJuros += "," + priceSimulado.getJuros().get(i);
        }
        stringJuros += "}";
        
        String stringAmort = "{" + priceSimulado.getAmort().get(0);
        for (int i = 1; i < priceSimulado.getAmort().size(); i++) {
            stringAmort += "," + priceSimulado.getAmort().get(i);
        }
        stringAmort += "}";
        
        String stringPmt = "{" + priceSimulado.getPmt().get(0);
        for (int i = 1; i < priceSimulado.getPmt().size(); i++) {
            stringPmt += "," + priceSimulado.getPmt().get(i);
        }
        stringPmt += "}";
        
        String stringSf = "{" + priceSimulado.getSf().get(0);
        for (int i = 1; i < priceSimulado.getSf().size(); i++) {
            stringSf += "," + priceSimulado.getSf().get(i);
        }
        stringSf += "}";
        
        try {
           String sql = "INSERT INTO tabela VALUES (default, "
                   + "'"+priceSimulado.getConta().getId()+"', "
                   + "'"+priceSimulado.getTipo()+"', "
                   + "'"+priceSimulado.getPv()+"', "
                   + "'"+priceSimulado.getN()+"', "
                   + "'"+priceSimulado.getI()+"', "
                   + "'"+stringSi+"', "
                   + "'"+stringJuros+"', "
                   + "'"+stringAmort+"', "
                   + "'"+stringPmt+"', "
                   + "'"+stringSf+"')";
           PreparedStatement pstm = banco.getCon().prepareStatement(sql);
           pstm.execute();
           
           String sql2 = "UPDATE conta SET divida = divida + "+ priceSimulado.getPmt().get(0) +" WHERE cpf = '"+ conta.getCpf()+"'";
           PreparedStatement pstm2 = banco.getCon().prepareStatement(sql2);
           pstm2.execute();
           
           JOptionPane.showMessageDialog(rootPane, "Emprestimo adicionado com sucesso");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        apagarComponentes();
        
    }//GEN-LAST:event_botaoPriceActionPerformed

    private void botaoSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSacActionPerformed
        
        sacSimulado.setConta(conta);
        
        String stringSi = "{" + sacSimulado.getSi().get(0);
        for (int i = 1; i < sacSimulado.getSi().size(); i++) {
            stringSi += "," + sacSimulado.getSi().get(i);
        }
        stringSi += "}";
        
        String stringJuros = "{" + sacSimulado.getJuros().get(0);
        for (int i = 1; i < sacSimulado.getJuros().size(); i++) {
            stringJuros += "," + sacSimulado.getJuros().get(i);
        }
        stringJuros += "}";
        
        String stringAmort = "{" + sacSimulado.getAmort().get(0);
        for (int i = 1; i < sacSimulado.getAmort().size(); i++) {
            stringAmort += "," + sacSimulado.getAmort().get(i);
        }
        stringAmort += "}";
        
        String stringPmt = "{" + sacSimulado.getPmt().get(0);
        for (int i = 1; i < sacSimulado.getPmt().size(); i++) {
            stringPmt += "," + sacSimulado.getPmt().get(i);
        }
        stringPmt += "}";
        
        String stringSf = "{" + sacSimulado.getSf().get(0);
        for (int i = 1; i < sacSimulado.getSf().size(); i++) {
            stringSf += "," + sacSimulado.getSf().get(i);
        }
        stringSf += "}";
        
        
        try {
           String sql = "INSERT INTO tabela VALUES (default, "
                   + "'"+sacSimulado.getConta().getId()+"', "
                   + "'"+sacSimulado.getTipo()+"', "
                   + "'"+sacSimulado.getPv()+"', "
                   + "'"+sacSimulado.getN()+"', "
                   + "'"+sacSimulado.getI()+"', "
                   + "'"+stringSi+"', "
                   + "'"+stringJuros+"', "
                   + "'"+stringAmort+"', "
                   + "'"+stringPmt+"', "
                   + "'"+stringSf+"')";
           PreparedStatement pstm = banco.getCon().prepareStatement(sql);
           pstm.execute();
           
           String sql2 = "UPDATE conta SET divida = divida + "+ priceSimulado.getPmt().get(0) +" WHERE cpf = '"+ conta.getCpf()+"'";
           PreparedStatement pstm2 = banco.getCon().prepareStatement(sql2);
           pstm2.execute();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        apagarComponentes();
        
    }//GEN-LAST:event_botaoSacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPrice;
    private javax.swing.JButton botaoSac;
    private javax.swing.JButton botaoSimular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTable tabelaPrice;
    private javax.swing.JTable tabelaSac;
    // End of variables declaration//GEN-END:variables

    private void preencherPriceSimulado(Tabela priceSimulado) {

        DefaultTableModel modeloTable = (DefaultTableModel) tabelaPrice.getModel();

        while (modeloTable.getRowCount() > 0) {
            modeloTable.removeRow(0);
        }
        
        i = 0;
        for (Double item : priceSimulado.getSi()) {
            modeloTable.addRow(new Object[]{formato.format(item), 
                formato.format(priceSimulado.getJuros().get(i)), 
                formato.format(priceSimulado.getAmort().get(i)), 
                formato.format(priceSimulado.getPmt().get(i)), 
                formato.format(priceSimulado.getSf().get(i))});
            i++;
        }
        i = 0;
            
    }

    private void preencherSacSimulado(Tabela sacSimulado) {
        
        DefaultTableModel modeloTable = (DefaultTableModel) tabelaSac.getModel();

        while (modeloTable.getRowCount() > 0) {
            modeloTable.removeRow(0);
        }
        
        i = 0;
        for (Double item : sacSimulado.getSi()) {
            modeloTable.addRow(new Object[]{formato.format(item), 
                formato.format(sacSimulado.getJuros().get(i)), 
                formato.format(sacSimulado.getAmort().get(i)), 
                formato.format(sacSimulado.getPmt().get(i)), 
                formato.format(sacSimulado.getSf().get(i))});
            i++;
        }
        i = 0;
    }
    
    private double somaPmt(Tabela tabela){
        
        double soma = 0;
        
        for (Double item : tabela.getPmt()) {
            soma += item;
        }
        
        return soma;
        
    }
    
    private void apagarComponentes() {
        
        DefaultTableModel modeloTable;
        
        modeloTable = (DefaultTableModel) tabelaPrice.getModel();

        while (modeloTable.getRowCount() > 0) {
            modeloTable.removeRow(0);
        }
        
        modeloTable = (DefaultTableModel) tabelaSac.getModel();

        while (modeloTable.getRowCount() > 0) {
            modeloTable.removeRow(0);
        }
        
        botaoPrice.setEnabled(false);
        botaoSac.setEnabled(false);
        
        jTextField2.setText(""+formato.format(conta.getDivida()));
        jTextField3.setText("");
        jTextField4.setText("");
        banco = new Banco();
        conta = new Conta();
        priceSimulado = new Tabela();
        sacSimulado = new Tabela();
        i = 0;
        
        
    }
    
}
